apiVersion: v1
kind: Service
metadata:
  name: nodeapi
  labels:
    run: nodeapi
spec:
  ports:
  - name: http
    port: 443
    targetPort: 3000
    protocol: TCP
  selector:
    app: nodeapi
  type: LoadBalancer
